# Generated by Django 2.1.2 on 2019-09-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190909_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('symbol', models.CharField(default='E', max_length=1)),
                ('game', models.ForeignKey(db_column='game_id', on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='flag',
            name='game',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='game',
        ),
        migrations.RemoveField(
            model_name='mine',
            name='game',
        ),
        migrations.DeleteModel(
            name='Flag',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Mine',
        ),
    ]
